asyncapi/parser-js

API.md, lib/models/asyncapi.js, lib/models/base.js, lib/models/components.js, lib/models/info.js, lib/models/message-trait.js, lib/models/message-traitable.js, lib/models/message.js, lib/models/oauth-flow.js, lib/models/operation-trait.js, lib/models/operation-traitable.js, lib/models/operation.js, lib/models/schema.js, lib/models/security-scheme.js, test/models/asyncapi_test.js, test/models/base_test.js, test/models/components_test.js, test/models/info_test.js, test/models/message-trait_test.js, test/models/message-traitable_test.js, test/models/oauth-flow_test.js, test/models/operation-trait_test.js, test/models/operation-traitable_test.js, test/models/operation_test.js, test/models/schema_test.js, test/models/security-scheme_test.js
Adds missing models and methods, i.e.:
* Components
* Traits
* SecurityScheme
* OAuthFlow
=> Add missing models and methods

lib/models/channel.js, lib/models/message-traitable.js, lib/models/operation-traitable.js, lib/models/server.js, test/models/channel_test.js, test/models/message-trait_test.js, test/models/message-traitable_test.js, test/models/message_test.js, test/models/operation-trait_test.js, test/models/operation-traitable_test.js, test/models/operation_test.js, test/models/server_test.js
Fixes #21 
Renames `protocolInfo` to `bindings` and adds bindings to Server object.
=> Fix bindings

lib/schema-parsers/openapi.js, package-lock.json, package.json
I ran `npm test` and all looks good, not sure if I can check something more manually
Fixes #36
=> Change openapi-schema-to-json-schema

.github/workflows/release.yml, README.md
- add docs generation to release pipeline so we do not have to remember about it on our own. Generated dosc will be pushed to repo with the same PR that will be created for package.json bump
=> chore: add docs generation to release pipeline

.github/workflows/pull-request-testing.yml, test/models/asyncapi_test.js
Pull requests should run all the tests so reviewers don't waste time on PR's which contains failed tests.
Fixes #73
=> Chore: Added new workflow for testing in pull requests

API.md, lib/models/schema.js, test/models/schema_test.js
=> fix: schema.type() docs

lib/models/schema.js, test/models/schema_test.js
- add `discriminator` function to schema model
Fixes #80
=> feat: add discriminator function to schema model

lib/models/schema.js, test/models/schema_test.js
- Added externalDocs function to Schema model
Resolves #95
=> feat: Add externalDocs function to Schema model

lib/models/schema.js, lib/utils.js
- use `.createMapOfType()` util method in Schema model.
- refactor `.findLocationOf()` method.
Resolves #107
=> refactor: use .createMapOfType() util method in schema.model

lib/utils.js, package-lock.json, package.json
- remove re2 that is not browser compatible
Fixes #123
=> fix: remove re2 that is not browser compatible

package-lock.json, package.json
- Add latest spec schema to properly validate headers object
This is a fix for one of the test cases in tck too
=> feat: Add latest spec schema to properly validate headers object

package-lock.json, package.json
- Add latest asyncapi spec after fix for minProperties
=> feat: Add latest asyncapi spec after fix for minProperties

package-lock.json, package.json
- Add latest spec schema to properly validate headers
=> feat: Add latest spec schema to properly validate headers

.gitignore, index.html, lib/parser.js, lib/utils.js, package-lock.json, package.json, test/asyncapiSchemaFormatParser_test.js, test/browser_test.js, test/customValidators_test.js, test/parse_test.js, test/sample_browser/asyncapi.yaml, test/sample_browser/index.html, test/testsUtils.js
- Parser failing for browser and tests to prevent it in future
See also #130
=> chore: Parser failing for browser and tests to prevent it in future

.github/workflows/automerge.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/welcome-first-time-contrib.yml
1. Added `sentiment-analysis.yml` to .github/workflows
2. Rename pull_request from line 4 to pull_request_target in .github/workflows/welcome-first-time-contrib.yml file
3. Rename the `automerge-release-pr-bump.yml`to `automerge.yml` and modify the if statement according to the instruction
Fixes #174
=> chore: Cleanup GitHub Actions workflows

.github/workflows/automerge.yml
Update automerge.yml
add-on fix for  #180
=> chore: Update automerge workflow to support dependabot

package-lock.json, package.json
=> chore(release): bump version to 1.0.0

.github/workflows/release.yml
- add twitter release tweet step to release workflow to automate such info announcement and making more noise about the project
=> ci: add twitter release tweet step to release workflow

.github/workflows/pull-request-testing.yml, .github/workflows/sentiment-analysis.yml
Ensured that tests and analysis are only run when PR is not in draft mode.
Fixes #200
=> chore: Disabled any testing on draft PR

lib/anonymousNaming.js, lib/models/asyncapi.js
This PR moves all the anonymous naming functionality to a separate file.
=> chore: Move anonymous naming functionality

lib/iterators.js, lib/models/asyncapi.js, types.d.ts
- Fixes types.d.ts duplicate type generation and.
- Fixes types.d.ts unwanted type generation.
=> fix: duplicate type problem and unresolved Schema type

README.md, lib/parser.js, package.json, test/parseFromUrl_test.js
- Add test for `parseFromUrl` function present in `parser.js` file.
- Wrap the exception thrown by `parseFromUrl` function in `parserError` object.
- Modified the `package.json` scripts to combine reports from multiple tests.
- Update README to add the Error Type.
=> test: add test for parseFromUrl function

lib/utils.js, test/parse_test.js, test/wrong/invalid-asyncapi.json, test/wrong/invalid-asyncapi.yaml
=> fix: wrong position info about errors in the root of the doc

README.md
Document how to use browser bundle:
- in html file
- in SPA application
Some people want use package in browser but don't know how.
=> docs: document how to use browser bundle

README.md
Updating the example shown in the README.md
Moving from `parseUrl` to `parseFromUrl`.
=> docs: update API in README from `parseUrl` to `parseFromUrl`

lib/customValidators.js, package-lock.json, package.json, test/customValidators_test.js
- update error title for unknown servers on Channel Object
- add additional test with multiple channels and multiple missed servers on Channel Object
asyncapi/spec#244
asyncapi/spec#255
asyncapi/spec#475
**Related PR(s)**
https://github.com/asyncapi/parser-js/pull/364
=> fix: update error title for unknown servers on Channel Object

package-lock.json, package.json
Update @asyncapi/specs to the latest (`2.9.0`) version with AsyncAPI `2.2.0` onboard.
=> feat: update @asyncapi/specs to the latest version

README.md
Update stringify docs:
- add example of stringified spec
- add info about prefix in JSON Pointers
See comment https://github.com/asyncapi/html-template/pull/286#issuecomment-986660092
=> docs: update stringify docs

lib/asyncapiSchemaFormatParser.js
In some NodeJS version we cannot use `Array.prototype.flat` function. I fix that and switch to implementation with `push` function.
Example problem in this PR https://github.com/asyncapi/website/pull/579
=> fix: do not use the Array.prototype.flat function

.github/workflows/link-check-cron.yml, .github/workflows/link-check-pr.yml, package-lock.json, package.json
This PR merges master into the next-major-spec branch.
=> chore: update with upstream master

.github/workflows/add-good-first-issue-labels.yml, .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml, .github/workflows/automerge-for-humans-merging.yml, .github/workflows/automerge-for-humans-remove-ready-to-merge-label-on-edit.yml, .github/workflows/automerge-orphans.yml, .github/workflows/automerge.yml, .github/workflows/autoupdate.yml, .github/workflows/bump.yml, .github/workflows/help-command.yml, .github/workflows/if-go-pr-testing.yml, .github/workflows/if-nodejs-pr-testing.yml, .github/workflows/if-nodejs-release.yml, .github/workflows/if-nodejs-version-bump.yml, .github/workflows/issues-prs-notifications.yml, .github/workflows/link-check-cron.yml, .github/workflows/link-check-pr.yml, .github/workflows/lint-pr-title.yml, .github/workflows/notify-tsc-members-mention.yml, .github/workflows/release-announcements.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/stale-issues-prs.yml, .github/workflows/welcome-first-time-contrib.yml, package-lock.json, package.json
There was a conflict that was preventing the bot to update the branch. Now this PR solves it.
=> chore: resolve merge conflicts on 2022-04-release branch

lib/asyncapiSchemaFormatParser.js
=> chore: add new mimetype

jest.config.ts, package-lock.json, package.json
As in title. Differences:
- without `@swc`: about 30s.
- with `@swc`: about 8s.
Of course in my machine. I also removed `json` and `lcov` coverage reports - atm we don't need that. We will enable them when we will need them.
cc @smoya 
Part of #481
Part of #482
=> refactor: use @swc/jest to speedup test execution

src/models/v2/channel.ts, src/models/v2/server.ts, src/schema-parser/avro-schema-parser.ts, src/spec-types/v2.ts, src/utils.ts
=> refactor: fix some bugs and smells

lib/asyncapiSchemaFormatParser.js
Refs https://github.com/asyncapi/spec/issues/830
=> chore: update release branch with 2.5.0 version

src/schema-parser/avro-schema-parser.ts, test/schema-parser/avro/asyncapi-avro-148-1.9.0.json, test/schema-parser/avro/avro-schema-parser.spec.ts
- Apply latest changes to the AVRO schema parser from https://github.com/asyncapi/avro-schema-parser/pull/154 PR
- Update tests
Part of #481 
Part of #482
Resolves #620
=> refactor: apply latest changes to the avro schema parser

README.md, package.json
Fix `prepublishOnly` script - https://github.com/asyncapi/parser-js/actions/runs/3188498283/jobs/5201297535
=> fix: prepublishOnly script

test/browser/sample-page.html
Not very relevant but fixing [this](https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=598&id=asyncapi_parser-js&open=AYMx-xFpxkxar1N4ENuE) Sonarcloud """bug""".
=> ci: fix Sonarcloud bug with HTML page

test/parse.spec.ts, test/validate.spec.ts
- check if spectral returns understandable error for invalid url reference  
- check if spectral returns understandable error for invalid local reference  
Resolves #224
Resolves #360
=> test: add tests for 224 and 360 issues

test/parse_test.js
Reverts asyncapi/parser-js#692
=> revert: reverts a previous commit

lib/asyncapiSchemaFormatParser.js
refs https://github.com/asyncapi/spec/issues/894
cc @magicmatatjahu @fmvilas
=> chore: added mime for new version 2.6.0

.github/workflows/bump.yml
As in title: add cli to ignore repos in bump workflow.
See https://github.com/asyncapi/cli/pull/376#issuecomment-1408733804
=> ci: add cli to ignore repos in bump workflow

.github/workflows/bump.yml
Ignore `java-template` in bumping
See comment https://github.com/asyncapi/java-template/pull/94#issuecomment-1419310564
=> ci: ignore java-template in bumping

package-lock.json, src/ruleset/v2/ruleset.ts, test/ruleset/rules/v2/asyncapi2-channel-no-query-nor-fragment.spec.ts
Fixes https://github.com/asyncapi/parser-js/issues/740.
https://github.com/asyncapi/parser-js/issues/740
=> fix: change severity for channel name validation rule

.all-contributorsrc, .github/workflows/help-command.yml, .gitignore, .sonarcloud.properties, README.md, docs/migrations/v1-to-v2.md, docs/ruleset/README.md, docs/ruleset/core-ruleset.md, docs/ruleset/recommended-ruleset.md, docs/ruleset/v2-core-ruleset.md, docs/ruleset/v2-recommended-ruleset.md, package-lock.json, package.json, src/ruleset/v2/ruleset.ts, test/ruleset/rules/v2/asyncapi2-message-examples.spec.ts, test/ruleset/tester.ts
> **Warning**
> This PR should be merged manually by using Merge with commit strategy. More info on https://github.com/asyncapi/community/issues/641
=> chore: merge `master` into `next-major-spec`

package-lock.json
This PR merges `master` into `next-major-spec` fixing conflicts.
> **Warning**
> This PR should be merged manually by using Merge with commit strategy. More info on https://github.com/asyncapi/community/issues/641
=> chore: merge `master` into `next-major-spec` fixing conflicts

package-lock.json
Same as https://github.com/asyncapi/parser-js/pull/806. 
But this time plase @smoya should merge manually instead of `/rtm` 😓 
cc @derberg
=> chore: merge master into next-major-spec fixing conflicts

package-lock.json, package.json
This PR updates the dependency version of `specs` to the newest one.
=> feat: update specs dependency

src/models/v2/asyncapi.ts, src/models/v3/asyncapi.ts, test/models/v2/asyncapi.spec.ts, test/models/v3/asyncapi.spec.ts
=> fix: resolve type mismatch in allServers and allChannels

src/models/v3/asyncapi.ts, src/models/v3/operation-reply.ts, src/models/v3/operation.ts
=> fix: use relative paths

package-lock.json, package.json
Remove dependencies rendered as obsolete by PR #756 and in turns, fix [CVE-2020-15366](https://github.com/advisories/GHSA-v88g-cgmw-v5xw).
=> fix: remove unused deps to fix CVE-2020-15366

src/models/utils.ts
with  the latest version of parser in `next-major-spec` I am getting this error:
https://github.com/asyncapi/glee/actions/runs/6929361068/job/18846911426?pr=589
=> fix: fix import statement

.changeset/bubble-beach.md
Changes Added.
Added the Parser to the turborepo. 
Added the required scripts of the turborepo to the root package.json file.
Added the changeset for the parser.
Related issue(s)
Related to: https://github.com/asyncapi/parser-js/issues/963
This pr follows the merge of https://github.com/asyncapi/parser-js/pull/1036
=> feat: added the changeset for the parser. 
