lib/parser.js
I have error for this yaml:
```
asyncapi: '2.0.0-rc1'
id: 'urn:test.dev'
info:
title: Тестовое апи
version: '1.0.0'
servers:
- url: https://test.dev
protocol: wss
channels:
/test/:
subscribe:
message:
payload:
type: string
examples: ['тестовая строка']
```
=> Fix incorrect determine length yamlOrJsonGoString

API.md, lib/models/asyncapi.js, lib/models/info.js, test/models/asyncapi_test.js, test/models/info_test.js
It was trying to create License and Contact objects without checking if their respective JSON definitions where present.
=> Fix a bug with empty License and Contact objects

.github/workflows/release.yml
- bring back dist dir to fix bundle script otherwise `npm run bundle` fails
- switch to `prepublishOnly` instead using `bundle` script directly
=> fix: bring back dist dir to fix bundle script

lib/parser.js, package-lock.json, package.json
Some time ago we moved all packages under `@asyncapi` scope and I forgot to bump one of the packages in parser to use dependency with a new name
I added `refactor` prefix cause I think this PR should not trigger release as this is purely cosmetical change as the dependency doesn't bring anything new.
=> refactor: use new version of asyncapi package

.gitignore
- remove `.keep` as `bundle.js` will alwasy be in `dist` dir
- remove dist from gitignore as now it is not published to npm. Now with each release bundle.js will be pushed to repo with PR that bumps package.json
=> feat: remove dist/bundle.js from gitignore to get it pushed to npm

lib/models/asyncapi.js, test/models/asyncapi_test.js, test/parse_test.js
- fixes #71
- Solves a problems with additional items are never checked by the recursive schema function.
- Solved tests failing on windows but not on linux.
=> Fix: additional items and properties are never discovered and tests failing on windows

lib/models/schema.js, test/models/schema_test.js
Add support for missing 'deprecated' attribute in AsyncAPI schemas. I'm still not 100% clear what ends up in the parser, and what is left for the JSON schema itself, but there doesn't seem to be any way to 'look through' the Schema object to reach these?
Fixes https://github.com/asyncapi/parser-js/issues/78
=> Add support for missing 'deprecated' attribute

lib/models/asyncapi.js, test/models/asyncapi_test.js
- add `hasMessages()` function to main model. You can easily evaluate if specification file has any messages, in components or inside the channels operations
Resolves #84
=> feat: Add hasMessages function to main model

lib/customValidators.js, lib/parser.js, lib/utils.js, test/customValidators_test.js
- checking if server security key maps to a corresponding  security schema in components
- checking if server security values is an empty array in cases when schema type is not `oauth2` or `openIdConnect`
- location finder now supports arrays, like servers.{server}.security
Resolves #10
=> feat: validate if server security has security schema and is valid

lib/models/operation.js, test/models/operation_test.js
- message function returns message and not null if index not provided
See also https://github.com/asyncapi/java-spring-template/issues/75 where the issue was noticed
=> fix: message function returns message and not null if index not provided

lib/asyncapiSchemaFormatParser.js, test/asyncapiSchemaFormatParser_test.js
- do not stop parsing if message payload is not provided. The payload is not a mandatory field for a message.
Once we merge this one I will make a PR to tck to pump parser version. This is what we will get:
- is
- will be
The drop on valid files by 2 is caused by https://github.com/asyncapi/parser-js/issues/136#issuecomment-668507568
The rest looks good
Fixes #136
=> fix: Do not stop parsing if message payload is not provided

lib/customValidators.js, lib/utils.js, test/asyncapiSchemaFormatParser_test.js, test/customValidators_test.js, test/parse_test.js
- Validate oauth2 or openIdConnect have scopes in server sec
- This PR will make these test cases to pass https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Security%20Requirement%20Object/invalid-oauth2-without-scopes.yaml and https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Security%20Requirement%20Object/invalid-openIdConnect-without-scopes.yaml
I think such validation would be also handlable with if/else statement in AsyncAPI JSON Schema (didn't check but I believe it is doable) but because we already had logic for validation of server security, it was easy to plug in there
=> feat: Validate oauth2 or openIdConnect have scopes in server sec

lib/customValidators.js, test/customValidators_test.js
- Revert wrong oauth2 or openIdConnect server sec info validation as discussed here https://github.com/asyncapi/tck/issues/22. I did not revert entire commit as there were good things like additional comments to code added, and the `offset` usage added to all tests.
=> feat: Revert wrong oauth2 or openIdConnect server sec info validation

README.md, lib/models/asyncapi.js, lib/models/schema.js, test/good/circular-refs.yaml, test/parse_test.js
Unfortunately, the functionality that I added was useless in action. I tried it in 2 templates and I realized that marking the object as circular only if one of its props is circular doesn't make sense.
[BREAKING CHANGE] now object doesn't have the `x-parser-circular` is some props are circular, instead, it gets `x-parser-circular-props` with proper functions on schema model (`circularProps` and `hasCircularProps`). Thanks to it later in the template I can easily eliminate traversing circular props, and still go through those that are not circular, not listed in `x-parser-circular-props`.
=> chore: Improve circular refs support with circularProps and hasCircularProps

lib/parser.js, test/parse_test.js
- References resolved wrong when parsing is done inside Promise.all(). It was caused by the fact that `$RefParser` was initialized globally and shared in concurrent parsing
=> chore: References resolved wrong when parsing is done inside Promise.all()

lib/utils.js, test/parse_test.js, test/wrong/good-ref-to-broken-file.yaml, test/wrong/good-refed-file.yml, test/wrong/refed-file-broken-schema.yml
- throw correct errors located in files that are $ref of another $ref. Without this fix, the user gets the wrong type error like `Cannot read property 'properties' of undefined`
Fixes #177
=> fix: throw correct errors located in files that are $ref of another $ref

lib/customValidators.js, lib/parser.js, lib/utils.js, test/customValidators_test.js
- added validateChannelNames test suite
- added validateChannelName validator
- added method to check for URL parameters in string with RegEx
Fixes #145
=> feat: add validation of query params in channel name

.github/workflows/release.yml
- This should fix a problem that twitting is to late and takes the name of next commiter, which is always asyncapi-bot that  commit version bump (https://twitter.com/AsyncAPISpec/status/1323225244274987008)
=> ci: move twitter step before PR creation step

lib/utils.js, test/customValidators_test.js
- channels with name / fail on validation
See also https://github.com/asyncapi/parser-js/pull/191#issuecomment-726451384
=> fix: channels with name / fail on validation

.github/workflows/release.yml
Since we introduced a step that validates what type of release we have (patch/minor/major) we have a problem with twitter step. It is not run when we do release, and instead, it runs next time we do the push, push commit with pump in package.json. As a result, in tweet, instead of putting the name of the user that is responsible for major/minor release, we put the name of the user that pushed bump commit, always bot user. 
This PR should fix it by checking the version from package.json on master against the version from package.json available in the workflow. Taken from https://github.com/EndBug/version-check#static-checking-with-your-latest-version-on-npm
=> ci: fix release workflow step that is responsible for handling twitter

.github/workflows/bump.yml
- we cannot react on release event, as by that time changes in package.json are not there yet, so this `npm run get-version --silent` gives you a version before the latest
- reacting right after release event there is a huge risk package is not yet there on npm. Reacting on push of bump commit makes the workflow error prone
=> ci: bump workflow to start on push instead of release

.github/workflows/pull-request-testing.yml, .github/workflows/release.yml
- I cannot set a requirement on testing workflow on PR level because currently its job name is the same as name in release workflow, not job but step but long term it can be confusing, better have the same job name everywhere
- test on node14 as we anyway already support node14 in generator
=> ci: rename pr testing job name and test node 14

package.json, test/browser_test.js, test/sample_browser/index.html
- console log everything that shows up in the browser console during browser tests
- cleanup of browser test must be done before and after test. If we do only after, the problem is that when the test fails, cleanup doesn't run
See also https://github.com/asyncapi/parser-js/pull/214
=> test: improve feedback loop from browser tests

package.json, test/browser_test.js
This time it should be fine. I rerun tests on mac in this PR over 5 times and it never failed
- again have to do fix to trigger release
- increase timeouts on tests for mac
=> fix: increase timeouts on tests for mac

package.json, test/asyncapiSchemaFormatParser_test.js, test/customValidators_test.js, test/parse_test.js, test/testsUtils.js
This PR resolves issue #140.
- moved `checkErrorWrapper` from `parse_test.js` to separate file `testsUtils.js`
- refactored `parse_test.js` to use `checkErrorWrapper` from `testsUtils.js`
- refactored `asyncapiSchemaFormatParser_test.js` to use `checkErrorWrapper` from `testsUtils.js`
- refactored `customValidators_test.js` to use `checkErrorWrapper` from `testsUtils.js`
- removed offsets where input is a string variable and not a file
- added execution of *nix commands through `shx` so they also work on Windows without any change
(`shx` wraps native Unix commands as `shx cp \"dist/bundle.js\"` to avoid errors like this on Windows platforms)
=> test: extract checkErrorWrapper and use it in other tests

README.md
After question in Slack, it became clear that just linking to the API is not quite enough. So I have added a small section explaining the general API approach.
=> docs: add small section explaining the API

test/models/schema_test.js
- Adds tests to Schema model to handle the cases when properties aren't provided in the json document that the Schema is initialised with.
Resolves #278
=> test: add schema tests for the cases where properties are missing

package-lock.json, package.json
see also https://github.com/asyncapi/spec/issues/536
it is supposed to work the same as here https://github.com/asyncapi/spec/pull/539 + npm release
relevant workflow configuration is in master already as it came from a global workflow https://github.com/asyncapi/parser-js/commit/c9d751ce3e5591f0b506db2a84b5dc6dff080f11
=> chore: enable releases for spec-related release branches

package-lock.json, package.json
Contributes to: asyncapi/spec#466
Signed-off-by: Dale Lane <dale.lane@uk.ibm.com>
=> chore: update version for updated spec

lib/anonymousNaming.js, lib/models/asyncapi.js, test/models/asyncapi_test.js
This PR fixes an issue where we assign parameters wrong ids.
Fixes https://github.com/asyncapi/parser-js/issues/325
=> feat: assigning schema id to parameter schemas in components

README.md, lib/asyncapiSchemaFormatParser.js, lib/models/message-traitable.js, lib/parser.js, lib/utils.js, package-lock.json, package.json, test/good/asyncapi-messages-example-headers.yml, test/good/asyncapi-messages-example-optional.yml, test/good/asyncapi-messages-example-payload.yml, test/good/asyncapi-messages-example.yml, test/models/message-trait_test.js, test/models/message-traitable_test.js, test/models/message_test.js, test/parse_test.js, test/wrong/invalid-asyncapi-messages-example.yml
I had to make fixes to PR from Laurent as like in case of `asyncapi-node` I did not notice changes were against 2.1
anyway, I'm confused about one thing, should these be changed too?:
- https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L12
- https://github.com/asyncapi/parser-js/blob/master/lib/asyncapiSchemaFormatParser.js#L44-L51
or should now the default schema depend on the version of the spec user uses, so if 2.0 then 2.0 and if 2.1 then 2.1?
Thoughts?
=> fix: use proper json schema and tests to point to 2.1

lib/parser.js
Specify (in TS types) arguments with ParserOptions type as optionals.
Fix #350
=> fix: specify arguments with ParserOptions type as optionals

lib/models/message.js, lib/models/operation.js, test/models/message_test.js, test/models/operation_test.js
- this PR will add the above functions to the `Message` and `Operation` classes.
Resolves #226
=> feat: added `traits()` and `hasTraits()` functions

lib/customValidators.js, lib/models/channel.js, lib/utils.js, test/customValidators_test.js, test/models/channel_test.js
JS parser changes to support a new `servers` field on the `channel` object.
Relates to PR https://github.com/asyncapi/spec/pull/531
https://github.com/asyncapi/spec/issues/244
https://github.com/asyncapi/spec/issues/255
https://github.com/asyncapi/spec/issues/475
=> feat: added servers field to channel object

lib/customValidators.js
This Pull request fixes issue #378 
Fix https://github.com/asyncapi/parser-js/pull/378
=> refactor: remove not needed semicolon

lib/models/base.js, types.d.ts
The `json()` method accepts an optional `key` argument. I'm fixing the TypeScript type definition.
=> fix: type of json() method

lib/models/schema.js, types.d.ts
The `constructor` was missing in the `Schema` type definition. This PR adds the missing JSDoc annotation and adds it to the `types.d.ts`.
Fixes #437
=> fix: missing constructor type definition

package-lock.json, package.json
This updates the asyncapi/specs dependency to 2.13.0-2022-01-release.1.
=> feat: update specs dependency to use release candidate with solace binding

.github/workflows/bump.yml, .github/workflows/if-go-pr-testing.yml, .github/workflows/if-nodejs-pr-testing.yml, .github/workflows/notify-tsc-members-mention.yml
This PR changes the base branch for the bump action so it only applies to dependants of the`next-major` branch, a branch that was recently created to work on the next major version (https://github.com/asyncapi/parser-js/issues/401).
Note that the target branch is (and should be) `next-major`. 
https://github.com/asyncapi/parser-js/issues/401
=> ci: set next-major branch as base branch for bump action

src/models/asyncapi.ts, src/models/contact.ts, src/models/index.ts, src/models/info.ts, src/models/license.ts, test/models/asyncapi.spec.ts, test/models/contact.spec.ts, test/models/info.spec.ts, test/models/license.spec.ts
This PR adds Info and the dependant models (Contact, License). It also allows to retrieve Info from the document root.
The models are based on the new Intent API (even though Info looks the same by now).
Pending things that can be out of this PR:
- How to handle retrocompatibility.
https://github.com/asyncapi/parser-js/issues/482
=> refactor: add info and dependant models

src/constants.ts, src/index.ts, src/models/base.ts, src/stringify.ts, src/utils.ts, test/stringify.spec.ts, test/utils.spec.ts
- Add `stringify` and `unstringify` functions - it's copy of the static methods of `AsyncAPIDocument`
- Add needed helpers
- Add extensions that we will use in next PRs
- Add relevant unit tests
Part of https://github.com/asyncapi/parser-js/issues/482
Part of https://github.com/asyncapi/parser-js/issues/421
=> refactor: add stringify functionality

package-lock.json, package.json, src/constants.ts, src/custom-operations/apply-traits.ts, src/custom-operations/index.ts, src/custom-operations/parse-schema.ts, src/index.ts, src/parse.ts, src/schema-parser/asyncapi-schema-parser.ts, src/schema-parser/index.ts, src/stringify.ts, src/types.ts, src/utils.ts, test/utils.spec.ts
- init custom parser functionality: `registerSchemaParser` etc.
- init custom operations like `applyTraits` or `parseSchemas`.
- without tests, I will add them soon.
Part of #481 
Part of #482
=> refactor: init custom parser functionality

package.json, src/constants.ts, src/models/asyncapi.ts, src/models/base.ts, src/models/mixins/bindings.ts, src/models/mixins/description.ts, src/models/mixins/external-docs.ts, src/models/mixins/index.ts, src/models/mixins/specification-extensions.ts, src/models/mixins/tags.ts, src/models/v2/asyncapi.ts, src/models/v3/asyncapi.ts, test/models/mixins/bindings.spec.ts, test/models/mixins/description.spec.ts, test/models/mixins/external-docs.spec.ts, test/models/mixins/inheritance.ts, test/models/mixins/specification-extensions.spec.ts, test/models/mixins/tags.spec.ts, test/models/v2/asyncapi.spec.ts
- add mixins for `tags`, `description`, `bindings`, `externalDocs` and specification extensions
- add needed functionality to extend models by mixins
- add unit tests for mixins and create helpers to check inheritance of mixins
Part of #481 
Part of #482
=> refactor: add needed mixins

lib/asyncapiSchemaFormatParser.js
Part of https://github.com/asyncapi/spec/issues/735
=> chore: update 2022-04-release branch

src/models/server-variable.ts, src/models/server-variables.ts, src/models/server.ts, src/models/v2/server-variable.ts, src/models/v2/server-variables.ts, src/models/v2/server.ts, src/models/v3/server-variable.ts, src/models/v3/server-variables.ts, src/models/v3/server.ts, test/models/v2/server-variable.ts, test/models/v2/server.spec.ts
Porting `server-variable` object to typescript. 
See also #482
=> refactor: port server-variable model to ts

src/custom-operations/index.ts, src/custom-operations/parse-schema.ts, src/index.ts, src/lint.ts, src/parse.ts, src/parser.ts, src/schema-parser/index.ts, src/types.ts, src/utils.ts, test/lint.spec.ts, test/parse.spec.ts, test/parser.spec.ts
Add `Parser` class. Having a different instance (of Parser) for validation/parsing is important from the point of view of tools for which the rules for Spectral will often change, e.g. `server-api`. Once the 2.0.0 version of the parser is released, people should be able to upload their own rules. This will also allow us to optimize the validation on the side of e.g. the Studio. 
Part of #481 
Part of #482
=> refactor: add Parser class

API.md, lib/models/operation-security-requirement.js, lib/models/operation.js, test/models/operation_test.js, types.d.ts
File                                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------------------|---------|----------|---------|---------|-------------------
All files                           |   95.87 |    88.33 |   97.32 |   98.21 |                   
lib                                |   96.29 |    88.79 |   99.24 |   98.85 |                   
anonymousNaming.js                |     100 |    95.45 |     100 |     100 | 28                
asyncapiSchemaFormatParser.js     |     100 |      100 |     100 |     100 |                   
constants.js                      |     100 |      100 |     100 |     100 |                   
customValidators.js               |   99.02 |    96.97 |     100 |     100 | 45,513,541-545    
index.js …
=> feat: add security field at the operation level

package-lock.json, package.json
Wondering if I could use some wildcard to not having to do this change every time we wanna merge a change.
=> chore: point @asyncapi/specs package to 2.14.0-2022-04-release.1

package.json
This PR adds the [agreed-upon branch for next major spec version](https://github.com/asyncapi/spec/issues/734#issuecomment-1077455953) going forward.
Related to https://github.com/asyncapi/spec/issues/691
=> chore: add next-major-spec prerelease

src/models/channel-parameter.ts, src/models/channel-parameters.ts, src/models/channel.ts, src/models/channels.ts, src/models/collection.ts, src/models/components.ts, src/models/contact.ts, src/models/correlation-id.ts, src/models/info.ts, src/models/license.ts, src/models/message-example.ts, src/models/message-trait.ts, src/models/message-traits.ts, src/models/message.ts, src/models/messages.ts, src/models/operation-trait.ts, src/models/operation-traits.ts, src/models/operation.ts, src/models/operations.ts, src/models/schema.ts, src/models/schemas.ts, src/models/server-variable.ts, src/models/server-variables.ts, src/models/server.ts, src/models/servers.ts, src/models/utils.ts
Add all missed interfaces that should be implemented in next PRs.
Part of #482 
Part of #481
=> refactor: add all missed interfaces

README.md, lib/parser.js
this PR is supposed to fix all the [dead links](https://github.com/asyncapi/parser-js/runs/6143265431?check_suite_focus=true) in markdown files across the repo.
=> docs: fix links in Markdown files

package.json
Relates to https://github.com/asyncapi/spec/issues/734#issuecomment-1077455953
This PR changes the `package.json` file to reflect the changes on the branch naming strategy for releasing; using `next-spec` and `next-major-spec` branches, plus `next-major` in this particular case.
=> ci(release): use new branch naming strategy

src/models/asyncapi.ts, src/models/channel.ts, src/models/message.ts, src/models/operation.ts, src/models/server.ts, src/models/v2/asyncapi.ts, src/models/v2/channel.ts, src/models/v2/message.ts, src/models/v2/operation.ts, src/models/v2/server.ts, src/utils.ts, test/models/asyncapi.spec.ts, test/models/v2/asyncapi.spec.ts, test/models/v2/channel.spec.ts, test/models/v2/message.spec.ts, test/models/v2/operation.spec.ts, test/models/v2/server.spec.ts
- add missed methods to models: `AsyncAPI`, `Server`, `Channel`, `Operation`, `Message`, mainly `servers()`, `channels()`, `operations()`, `messages()`
- add unit tests
Part of #481 
Part of #482
=> refactor: add missed methods to models

lib/models/operation.js, test/models/operation_test.js
If message object is
```
message:
oneOf:
- $ref: '#/components/messages/ixOtaResponse'
```
Then parser will return
```
channel.subscribe().hasMultipleMessages() => false
channel.subscribe().messages() => [ Message{ ... } ]
channel.subscribe().message() => Message{ ... }
```
Fixes #475
=> fix: case when message is oneOf for one element

src/schema-parser/asyncapi-schema-parser.ts, test/schema-parser/asyncapi-schema-parser.spec.ts
As mentioned in https://github.com/asyncapi/parser-js/pull/577#discussion_r952480918, the returned path should be relative to the payload and should not include the path to the payload itself. 
https://github.com/asyncapi/parser-js/issues/480
=> refactor: fix AsyncAPI Schema Parser error path

package-lock.json, package.json, src/schema-parser/raml-schema-parser.ts, test/schema-parser/raml/complex.json, test/schema-parser/raml/invalid.json, test/schema-parser/raml/raml-schema-parser.spec.ts, test/schema-parser/raml/simple.json
This PR does the following:
- Ports https://github.com/asyncapi/raml-dt-schema-parser to TypeScript.
- Makes it compliant with the [new interface](https://github.com/asyncapi/parser-js/issues/480) for Schema Parsers (new `validate()` method).
> **Note**
> Schema validation is done through https://github.com/raml-org/webapi-parser. It does not provide a real JSON Path value for validation errors or something that can be really transformed in all cases. By now, path will point to the message payload but we can keep investigating other solutions.
https://github.com/asyncapi/parser-js/issues/480
=> refactor: add RAML Schema Parser

src/models/message-trait.ts, src/models/v2/message-trait.ts, test/models/v2/message-trait.spec.ts, test/models/v2/message.spec.ts
Add `schemaFormat` method to the `Message model` and `MessageTrait model`. Atm we don't have clarification if we wanna go forward with proposal https://github.com/asyncapi/spec/pull/797 so will add `schemaFormat` to mentioned models and (maybe) in the future deprecate that method.
cc @smoya 
Part of:
#482 
#481
=> refactor: add schemaFormat method to the Message model

src/constants.ts, src/schema-parser/asyncapi-schema-parser.ts, src/schema-parser/spectral-rule-v2.ts, src/spectral.ts, test/spectral.test.ts
Add rule to check if AsyncAPI document is defined or not.
cc @smoya 
Part of #481 
Part of #482
=> refactor: add rule to check if AsyncAPI document is defined or not

src/models/operation-trait.ts, src/models/security-requirement.ts, src/models/security-requirements.ts, src/models/server.ts, src/models/v2/operation-trait.ts, src/models/v2/security-requirement.ts, src/models/v2/security-requirements.ts, src/models/v2/server.ts, test/models/v2/operation-trait.spec.ts, test/models/v2/security-requirement.spec.ts, test/models/v2/security-requirements.spec.ts, test/models/v2/server.spec.ts
This PR adds the models for `SecurityRequirement` and `SecurityRequirements` based on https://github.com/asyncapi/parser-api/pull/71.
https://github.com/asyncapi/parser-js/issues/482
=> refactor: add SecurityRequirement(s) models

src/models/operation-trait.ts, src/models/operation.ts, src/models/v2/operation-trait.ts, test/models/v2/operation-trait.spec.ts, test/models/v2/operation.spec.ts
This PR simplifies `OperationTrait` based on last changes found in https://github.com/asyncapi/parser-api/pull/71#issuecomment-1235603136.
Also added `isSend` and `isReceive` methods to `Operation`.
https://github.com/asyncapi/parser-js/issues/401
=> refactor: simplify operation traits based on parser-api

src/models/channels.ts, src/models/collection.ts, src/models/messages.ts, src/models/operations.ts, src/models/servers.ts, src/models/v2/channels.ts, src/models/v2/messages.ts, src/models/v2/operations.ts, src/models/v2/servers.ts, test/models/collection.spec.ts, test/models/v2/channels.spec.ts, test/models/v2/messages.spec.ts, test/models/v2/operations.spec.ts, test/models/v2/servers.spec.ts
This PR adds:
- `FilterBySend()` method to `Messages`, `Servers`, `Operations`, `Channels` models.
- `FilterByReceive()` method to `Messages`, `Servers`, `Operations`, `Channels` models.
All changes are done based on the Parser-API; last development in particular can be found in https://github.com/asyncapi/parser-api/pull/71.
https://github.com/asyncapi/parser-js/issues/401
=> refactor: add filters to some collections

src/models/components.ts, src/models/extension.ts, src/models/schema.ts, src/models/security-scheme.ts, src/models/v2/bindings.ts, src/models/v2/components.ts, src/models/v2/extension.ts, src/models/v2/extensions.ts, src/models/v2/mixins.ts, src/models/v2/schema.ts, src/models/v2/security-scheme.ts, src/spec-types/v2.ts, test/models/v2/components.spec.ts, test/models/v2/external-docs.spec.ts
This PR does a cleanup and sync with the latest changes on `parser-api` made in https://github.com/asyncapi/parser-api/pull/71#issuecomment-1239379887.
- https://github.com/asyncapi/parser-js/issues/481
- https://github.com/asyncapi/parser-js/issues/482
=> refactor: cleanup interfaces + add missing methods from parser-api

README.md
Update Readme.md with informations:
- add installation guide
- add examples
- update `custom parsers` section
- update `stringify` section
- update `develop` section
Other section will be updated in next PRs.
cc @smoya 
Part of #481
Part of #482
=> refactor: update Readme.md v1

.eslintrc, src/iterator.ts, test/iterator.spec.ts
This PR adds an iterator for traversing AsyncAPI documents. It is based in the current one. See https://github.com/asyncapi/parser-js/blob/master/lib/iterators.js
https://github.com/asyncapi/parser-js/issues/481
=> refactor: add iterator for traversing an AsyncAPI doc

.eslintignore, .gitignore, package.json, tsconfig.cjs.json, tsconfig.json
Export `cjs` and `esm` (with TS typings) modules from package. It's needed to packages which will consume parser-js. `ESM` is for website and treeshakable apps and `CJS` is for NodeJS app (but never versions can use ESM).
cc @smoya 
Part of #481 
Part of #482
=> refactor: export cjs and esm modules

README.md, src/index.ts, src/models/v2/channel.ts, src/old-api/converter.ts, test/old-api/converter.spec.ts, test/old-api/iterator.spec.ts
- fix TS imports: in CLI integration TSCompiler throws some warnings related to typings.
- change name `migrateToOldAPI` to `convertToOldAPI`.
- Update Readme
Part of #481 
Part of #482
=> refactor: fix TS imports and change name of migrator to converter

lib/models/server.js, package-lock.json, package.json, test/models/server_test.js
This PR adds support for Tags on Server model. They can be used for providing metadata, including the environment such as `production`, `development`, etc.
https://github.com/asyncapi/spec/issues/654
=> feat: add support for tags field on Server model

package-lock.json, package.json, src/parser.ts, src/resolver.ts, src/spectral.ts, src/stringify.ts, test/mocks/simple-message.yaml, test/resolver.spec.ts
Add possibility to pass custom resolvers. With `json-schema-ref-resolvers` we have possibility to pass custom ref resolvers. Atm we use that feature in Generator and in ServerAPI. Unfortunately, ref-resolver from Spectral doesn't have such a thing, so that PR "wraps" default Spectral resolvers with adding similar functionality. Of course that feature will be used only by us, so I annotated that feature by `__unstable` prefix. Spectral team is preparing to switch to the `json-schema-ref-parser` and we will provide this functionality when Spectral will support it natively.
cc @smoya 
Part of #481 
Part of #482
=> refactor: add possibility to pass custom resolvers (unstable)

src/from.ts, src/index.ts, src/old-api/index.ts, src/parse.ts, src/utils.ts, src/validate.ts, test/from.spec.ts, test/parse.spec.ts, webpack.config.js
- Export several functions needed by Studio's integration and Generator's integration.
- Export `extras` in `parse()` output - we need `document` Spectral's instance to get location/range of given JSON Path.
- Fix import in `from` file.
Part of https://github.com/asyncapi/parser-js/issues/481
=> refactor: exports extras and missed things

src/models/asyncapi.ts, src/models/v3/asyncapi.ts, src/models/v3/binding.ts, src/models/v3/bindings.ts, src/models/v3/extension.ts, src/models/v3/extensions.ts, src/models/v3/external-docs.ts, src/models/v3/mixins.ts, src/models/v3/tag.ts, src/models/v3/tags.ts, src/spec-types/index.ts, src/spec-types/v3.ts, src/types.ts
Init models and types for `v3` spec to enable contributions.
cc @smoya
=> chore: init models for v3 spec

README.md
- remove info about `v3` of spec (we don't have, yet)
- add info about helper functions in models.
cc @smoya 
Part of https://github.com/asyncapi/parser-js/issues/481
=> refactor: update Readme.md

src/custom-operations/anonymous-naming.ts, src/models/schema.ts, src/models/v2/schema.ts, src/models/v2/schemas.ts, test/models/v2/schema.spec.ts
This PR renames the `schema.uid()` method to become `schema.id()` to be consistent with all the other models (which are using `id()` as well).
The change in the `parser-api` can be seen [here](https://github.com/asyncapi/parser-api/pull/71/commits/0ae8f98405ed49e26bb46b7d73eea5efd51f1d4f).
=> fix: change schema.uid() method to schema.id()

package-lock.json, package.json
This PR updates `@spectral/rulesets` package to `1.14.1` that includes [this](https://github.com/stoplightio/spectral/pull/2284) fix.
Also fixes the lockfile version to become version 2, and updates:
- `@stoplight/spectral-core` from `1.14.1` to `1.14.2`
- `@asyncapi/specs` from `3.1.0` to `3.2.1`
=> fix: update Spectral ruleset fixing examples validation

src/index.ts, src/schema-parser/spectral-rule-v2.ts, src/types.ts
This PR exports some types that are required by other packages. In particular, by [this avro-schema-parser PR](https://github.com/asyncapi/avro-schema-parser/pull/168).
https://github.com/asyncapi/avro-schema-parser/issues/166
=> feat: export `AsyncAPISchema` and `v2` types

src/models/security-requirement.ts, src/models/security-scheme.ts, src/models/v2/security-scheme.ts, test/models/v2/security-requirement.spec.ts, test/models/v2/security-scheme.spec.ts, test/models/v2/server-variable.spec.ts
Add missed methods to the `SecurityScheme` model - `name()`.
I don't know if we should have methods like `hasName`, `hasScheme` for every optional fields. What do you think?
Blocks https://github.com/asyncapi/markdown-template/pull/312
cc @smoya
=> fix: add missed methods to the SecurityScheme model

src/models/operation-trait.ts, src/models/operation.ts, src/models/v2/operation-trait.ts, src/models/v2/operation.ts, src/models/v3/operation-trait.ts, src/models/v3/operation.ts, src/spec-types/v3.ts, test/models/v2/operation-trait.spec.ts, test/models/v2/operation.spec.ts, test/models/v3/operation-trait.spec.ts, test/models/v3/operation.spec.ts
Remove `action` and `channel` fields from Operation Trait Object.
https://github.com/asyncapi/spec/issues/856
=> fix: remove action and channel fields from Operation Trait Object

test/parse_test.js
Test locally passes, but problem is in CI side, so I will update test to be less restricted. Hopefully it should fix problem.
=> test: add less restricted test for memory usage

test/parse_test.js
Skip memory usage test due to problems. We don't want block the `2.6.0` release. We should check that after spec release what's going wrong.
=> test: skip memory usage test

.github/workflows/add-good-first-issue-labels.yml
Updated release branch
cc @derberg
=> chore: update release branch

package-lock.json, src/models/correlation-id.ts, src/models/oauth-flow.ts, src/models/v2/components.ts, src/models/v2/correlation-id.ts, src/models/v2/oauth-flow.ts, src/models/v2/operation-trait.ts, src/models/v2/operation.ts, test/models/v2/correlation-id.spec.ts, test/models/v2/oauth-flow.spec.ts, test/models/v2/operation.spec.ts
Update models with latest `parser-api`:
- make `location` in CorrelationId required
- add missed methods to the OAuthFlow object
- update Operation and OperationTrait objects
- add tests
See https://github.com/asyncapi/parser-api/blob/master/docs/v1.md
and https://github.com/asyncapi/parser-api/pull/86
=> fix: update models with latest parser-api

src/ruleset/ruleset.ts, test/ruleset/rules/asyncapi-document-unresolved.spec.ts
Validate unparsed AsyncAPI document (before `$ref`s resolving).
=> feat: validate unparsed AsyncAPI document

package.json
Fixes https://github.com/asyncapi/generator/issues/927
Even though this dependency will be out once we remove schema parsers from this repo in favor of their own repo. See https://github.com/asyncapi/openapi-schema-parser/pull/142#discussion_r1153125770
=> fix: pin @openapi-contrib/openapi-schema-to-json-schema to ~3.2.0

src/models/operation-reply.ts, src/models/operation.ts, src/models/v3/operation-reply.ts, src/models/v3/operation.ts, src/spec-types/v3.ts, test/models/v3/operation-reply.spec.ts, test/models/v3/operation.spec.ts
Update v3 models:
- fix models from https://github.com/asyncapi/spec/pull/847
- add unit tests
See also #732
=> chore: v3 request reply support

src/ruleset/v2/ruleset.ts, test/ruleset/rules/v2/asyncapi2-message-examples.spec.ts
Small change to skip the validation of message example objects when a `schemaFormat` is
set. This allows the parser to validate schemas with non default schemaFormats that are also
providing examples.
This does mean if anyone manually sets `schemaFormat` to the default the examples will not
be checked. Also it does not validate the examples against the schema for non default formats
so they may be incompatible 
Fixes #772
=> fix: skip message object example validation for non default schemaFormats

src/ruleset/v2/ruleset.ts, test/ruleset/rules/v2/asyncapi2-message-examples.spec.ts, test/ruleset/tester.ts
due to a quirk of how nimma generates the evaluation logic for checking fields in objects inside an array whilst filtering it is possible to get an npe. Adding specific checks against this.
Fixes #784
=> fix: null check when checking schemaFormat in array items

CODEOWNERS
Let's be honest. Since v2 this is almost completely different projects. I did not follow development and have no clue what is happening with the code 😅 and TS definitely do not encourage me to look closely into it 🤣 
Enough great maintainers here. I also step down as owner of custom schema parsers
=> chore: remove @derberg from `CODEOWNERS`

package-lock.json, src/models/message-trait.ts, src/models/schema.ts, src/models/v2/message-trait.ts, src/models/v2/message.ts, src/models/v2/schema.ts, src/models/v3/message-trait.ts, src/models/v3/message.ts, src/models/v3/schema.ts, src/spec-types/v3.ts, src/utils.ts, test/models/v2/message.spec.ts, test/models/v2/schema.spec.ts, test/models/v3/message-trait.spec.ts, test/models/v3/message.spec.ts, test/models/v3/schema.spec.ts
This PR adds the required changes for supporting [Multi-format schemas](https://github.com/asyncapi/spec/issues/622).
The API changes are in this`parser-api` PR https://github.com/asyncapi/parser-api/pull/86 waiting to be reviewed.
Replaces https://github.com/asyncapi/parser-js/pull/785
https://github.com/asyncapi/spec/issues/622
=> feat: add support for multi-format schema

src/ruleset/formats.ts, src/ruleset/functions/documentStructure.ts, src/ruleset/functions/unusedComponent.ts, src/ruleset/ruleset.ts, src/ruleset/v2/ruleset.ts, test/parse.spec.ts, test/ruleset/formats.spec.ts
This PR removes the need for creating new Spectral ruleset formats matching new AsyncAPI versions.
This translates to the removal of the requirement of making changes every time we add a new version into @asyncapi/specs package. It might be some exceptions in the case we, for example, add a new major spec version, where rules won't apply, and manual changes (and expected I would say) will need to be done, but will be close to as simple as including that new version in the allowed formats in ruleset.
This PR enables future support for v3 of the spec in a very easy way (will come in a new PR).
https://github.com/asyncapi/parser-js/issues/817
cc @jonaslagoni @magicmatatjahu @Amzani @fmvilas
=> refactor: match Spectral formats based on schemas found in @asyncapi/specs pkg

package-lock.json, package.json, src/ruleset/v2/functions/messageExamples-spectral-rule-v2.ts, src/ruleset/v2/functions/messageExamples.ts, src/ruleset/v2/ruleset.ts, test/ruleset/rules/v2/asyncapi2-message-examples-spectral-v2.spec.ts, test/ruleset/rules/v2/asyncapi2-message-examples.spec.ts, test/ruleset/tester.ts
validate message object examples against the schemas in the
object by parsing the schemas using spectral before validating
this proves that the examples are valid.
Contributes to: #781
Signed-off-by: Chris Patmore <chrism.patmore@btinternet.com>
=> feat: validate message object examples with spectral schemas

src/models/operation.ts, src/models/v2/operation.ts, test/models/v2/operation.spec.ts
Fixes https://github.com/asyncapi/parser-js/issues/831.
https://github.com/asyncapi/parser-js/issues/831
=> fix: add reply() to the Operation model

src/models/v3/asyncapi.ts, test/models/v3/asyncapi.spec.ts
Fixes https://github.com/asyncapi/parser-js/pull/526#discussion_r1229375542.
cc @jonaslagoni
=> fix: return proper schemas in asyncapi.schemas() method

src/models/v3/message.ts, test/models/v3/message.spec.ts
Fixes https://github.com/asyncapi/parser-js/issues/838.
This PR fixes `message.channels()` method that was not including the channels in the root AsyncAPI document that included such a message.
It also uncomment and fix all tests that, for some reason, were skipped.
https://github.com/asyncapi/parser-js/issues/838
=> fix: include all channels in message.channels()

package-lock.json, package.json, src/ruleset/v2/functions/messageExamples-spectral-rule-v2.ts, src/ruleset/v2/functions/messageExamples.ts, src/ruleset/v2/ruleset.ts, test/ruleset/rules/v2/asyncapi2-message-examples-spectral-v2.spec.ts, test/ruleset/rules/v2/asyncapi2-message-examples.spec.ts, test/ruleset/tester.ts
This PR contains the merge from `master` into `next-major-spec`. 
> **Warning**
> This PR should be merged manually by using Merge with commit strategy. More info on https://github.com/asyncapi/community/issues/641
=> feat: merge master into next-major-spec

README.md
This PR updates the compatibility matrix between the Parser-JS, Parser-API, and AsyncAPI Spec version.
=> docs: state support for parser-api v2 in compatibility matrix

src/models/asyncapi.ts, src/parse.ts, test/parse.spec.ts
This PR fixes the parser-api version in use from `1` to `2.0.0`. It moves the value to a constant set in the same file as `AsyncAPIDocumentInterface` is declared.
=> fix: set proper parser-api version

src/document.ts, src/models/asyncapi.ts, test/document.spec.ts
This PR fixes a problem where `isAsyncAPIDocument` cannot recognize parsed documents which means a lot of support functions are not working correctly.
=> fix: isAsyncAPIDocument not recognizing correct documents

src/models/message-trait.ts, src/models/v2/message-trait.ts, src/models/v3/message-trait.ts, src/spec-types/v3.ts, test/custom-operations/apply-traits-v3.spec.ts, test/models/v2/channel.spec.ts, test/models/v2/message-trait.spec.ts, test/models/v2/server.spec.ts, test/models/v3/channel.spec.ts, test/models/v3/message-trait.spec.ts, test/models/v3/message.spec.ts, test/models/v3/operation-reply.spec.ts, test/models/v3/operation.spec.ts, test/models/v3/server.spec.ts
Removes the `messageId()` function from the Message and MessageTrait objects. Keeps the same behavior on v2 but it doesn't look for `messageId` on v3. Now we only have one method to grab the id of a message and it's `.id()`.
Also, now `.hasMessageId()` now always returns `false` for v3.
https://github.com/asyncapi/spec/issues/978
=> feat!: remove messageId()

README.md, src/models/asyncapi.ts
After recent changes made in https://github.com/asyncapi/parser-js/pull/889, this latest version of the Parser only supports Parser-API v3 instead of v2.
This PR fixes that.
https://github.com/asyncapi/parser-js/pull/889
=> fix: change ParserAPIVersion constant to 3

src/models/utils.ts, src/models/v2/asyncapi.ts, src/models/v3/asyncapi.ts, test/models/v2/asyncapi.spec.ts, test/models/v3/asyncapi.spec.ts
Fixes https://github.com/asyncapi/parser-js/issues/896
https://github.com/asyncapi/parser-js/issues/896
=> fix: doc.allSchemas() skips now duplicates

src/document.ts, test/document.spec.ts
This PR fixes that we hardcoded a number to check the parser API when checking whether a document is from this parser version or not. This causes the check to fail, even though it was correct.
Related to https://github.com/asyncapi/html-template/issues/456
=> fix: wrong parserAPI number being checked

src/ruleset/index.ts, src/ruleset/v3/functions/operationMessagesUnambiguity.ts, src/ruleset/v3/index.ts, src/ruleset/v3/ruleset.ts, test/custom-operations/parse-schema-v3.spec.ts, test/ruleset/rules/v3/asyncapi3-operation-messages-from-referred-channel.spec.ts, test/ruleset/tester.ts
Part of https://github.com/asyncapi/spec/issues/991
This PR adds all the scaffolding for adding Spectral rules to v3 plus [the first of three new rules](https://github.com/asyncapi/spec/issues/991#issuecomment-1825700075) related with https://github.com/asyncapi/spec/issues/991.
This rule, in particular, checks that operation messages, no matter where they are located, need to point to messages from the channel specified in its channel field.
https://github.com/asyncapi/spec/issues/991
=> feat: add Spectral rule to validate operation messages

src/constants.ts, src/custom-operations/apply-traits.ts, src/custom-operations/apply-unique-ids.ts, src/custom-operations/index.ts, src/models/v3/channel.ts, src/models/v3/message.ts, src/models/v3/operation-reply.ts, src/models/v3/operation.ts, src/parse.ts, src/spec-types/v3.ts, test/custom-operations/apply-traits-v3.spec.ts, test/custom-operations/apply-unique-ids.spec.ts, test/models/v3/operation-reply.spec.ts, test/models/v3/server.spec.ts
This PR fixes a bunch of different edge cases with traits and ID's not being correctly created. Ontop of this, reply.messages had incorrect type as it's an array of messages NOT record, this is a breaking change.
Fixes https://github.com/asyncapi/parser-js/issues/873
Fixes https://github.com/asyncapi/parser-js/issues/856
Only one approach is needed, this PR or https://github.com/asyncapi/parser-js/pull/895 for solving https://github.com/asyncapi/parser-js/issues/873
=> fix!: traits, id and reply problems for v3

.all-contributorsrc, .github/workflows/automerge.yml, .github/workflows/update-docs-on-docs-commits.yml, CODEOWNERS, README.md, package-lock.json, package.json
> [!WARNING]  
> This PR should be merged manually by using Merge with commit strategy. More info on https://github.com/asyncapi/community/issues/641
=> chore: merge `master` into `next-major-spec`

.sonarcloud.properties, src/spec-types/v3.ts
Code duplication analysis makes sense most of the time. However, for models and types related with different versions of the spec, duplication is completely expected. 
[This PR](https://github.com/asyncapi/parser-js/pull/526) is blocked by such analysis.
This PR adds `src/spect-types/*.ts` to the previously existing list of exclusions. After that change, SonarCloud analysis should stop complaining about [this](https://sonarcloud.io/component_measures?metric=new_duplicated_lines_density&selected=asyncapi_parser-js%3Asrc%2Fspec-types%2Fv3.ts&view=list&pullRequest=526&id=asyncapi_parser-js).
=> ci: disable code duplication analysis for files under src/spec-types

src/custom-operations/apply-unique-ids.ts, src/parse.ts, test/custom-operations/apply-traits-v3.spec.ts, test/custom-operations/apply-unique-ids.spec.ts
Once before I implemented this functionality incorrectly. this PR fixes that operations, channels, and messages could not be iterated between each other. On top of that, the functionality did not work when references were local files, this has also been fixed. 
Raised on slack: https://asyncapi.slack.com/archives/CQVJXFNQL/p1707760039073239
=> fix: iterating between operations, channels and messages

src/custom-operations/apply-traits.ts, test/validate.spec.ts
Fixes https://github.com/asyncapi/parser-js/issues/996
The current AsyncAPI spec (v3.0.0) support traits only at:
- [Message Object level](https://www.asyncapi.com/docs/reference/specification/v3.0.0#messageTraitObject)
- [Operation Object level](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationTraitObject)
Channels traits are not supported, however for some reason we added such support in our Parser code. 
This was causing a bug (linked above).
https://github.com/asyncapi/parser-js/issues/996
=> fix: remove unexpected support for traits at Channel Object level

src/ruleset/v2/ruleset.ts, test/validate.spec.ts
The workflow that [validates examples](https://github.com/asyncapi/spec/blob/master/.github/workflows/validate-examples.yml) in the Spec repo is failing due to the [following reason](https://github.com/asyncapi/spec/actions/runs/9481679937/job/26125504690#step:5:46):
> examples/adeo-kafka-request-reply-asyncapi.yml
Error:  217:11  error  asyncapi2-schema-examples  "0" property type must be string  components.schemas.RequesterCode.examples[0]
Error:  244:11  error  asyncapi2-schema-examples  "0" property type must be string  components.schemas.BuCode.examples[0]
Besides the example is ok or not, that rule should not apply to any v3 document because it is not a valid v3 rule (target paths inside the rule are exclusive for v2). I believe I missed this one when filtering rules …
=> fix: remove v2 Spectral schema rules from v3 rules

.changeset/smooth-pumas-deliver.md, packages/parser/src/parse.ts, packages/parser/test/parse.spec.ts
This PR removes forceful normalization of YAML files to JSON format to fix https://github.com/asyncapi/parser-js/issues/936, which in its turn lays the foundation for reporting correct `range` values in error diagnostics for YAML files in `Studio`.
Related to https://github.com/asyncapi/parser-js/issues/1012
=> fix: remove forceful normalization of YAML to JSON

README.md
Fix the stringify example broken link
=> docs: fix stringify example broken link in README

.changeset/new-ears-clap.md, package-lock.json, packages/parser/package.json
Builds upon https://github.com/asyncapi/parser-js/pull/1056 by adding the needed changeset file so that a new minor version can be released.
=> chore(deps): bump jsonpath-plus to ^10.0.0 to mitigate CVE-2024-21534

README.md
- Links in Readme were not working.
=> docs: update links to new monorepo ones

packages/parser/src/ruleset/v2/functions/schemaValidation.ts, packages/parser/test/ruleset/rules/v2/asyncapi2-schema-examples.spec.ts
The spectral rule asyncApi2SchemaValidation currently enforces that all examples have the same type as the schema type. However, we believe that there are cases in AsyncAPI, where it is needed to accept string examples regardless of the schema type.
_To Reproduce:_
1. Use the AsyncAPI document: https://github.com/asyncapi/spec/issues/1038#issuecomment-1969489452
2. Open it in AsyncAPI studio
3. See the error: 66:11    error  asyncapi-schema-examples   "0" property type must be object components.schemas.io.github.springwolf.examples.kafka.dtos.XmlPayloadDto.examples[0]
- https://github.com/asyncapi/parser-js/issues/997
- https://github.com/stoplightio/spectral/issues/2624
=> fix: always allow schema string examples

turbo.json
This PR instructs `turbo` to wait for the build of `@asyncapi/parser` before executing `turbo run test`.
=> chore: add dependency on building `@asyncapi/parser` for `turbo run test`
